# fly.toml app configuration file generated for news-api-delicate-wind-709 on 2024-07-16T12:17:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-api-delicate-wind-709'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
